import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#393939",
        "primary-fixed": "#ffdbca",
        "secondary-container": "#474746",
        "text-muted": "#737373",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#9a9a9a",
        secondary: "#c8c6c5",
        "error-container": "#93000a",
        "on-surface": "#e5e2e1",
        "on-primary-fixed": "#341100",
        "outline-variant": "#584237",
        background: "#131313",
        "surface-container-highest": "#353535",
        primary: "#ffb690",
        "surface-variant": "#353535",
        "inverse-primary": "#9d4300",
        "on-secondary-fixed": "#1b1c1c",
        "tertiary-fixed": "#e3e2e2",
        "on-primary-container": "#582200",
        "surface-container-low": "#1c1b1b",
        "secondary-fixed": "#e4e2e1",
        "on-tertiary-fixed-variant": "#464747",
        "on-background": "#e5e2e1",
        "on-tertiary-container": "#313232",
        "on-tertiary": "#2f3131",
        "on-secondary": "#303030",
        "on-surface-variant": "#e0c0b1",
        "tertiary-fixed-dim": "#c7c6c6",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-border": "#333333",
        tertiary: "#c7c6c6",
        "on-secondary-fixed-variant": "#474746",
        "on-secondary-container": "#b7b5b4",
        surface: "#131313",
        "inverse-surface": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c5",
        "on-primary": "#552100",
        outline: "#a78b7d",
        "on-error": "#690005",
        "inverse-on-surface": "#313030",
        "surface-tint": "#ffb690",
        "surface-dim": "#131313",
        "primary-container": "#f97316",
        "surface-container-high": "#2a2a2a",
        error: "#ffb4ab",
        "primary-fixed-dim": "#ffb690",
        "surface-container": "#201f1f",
        "on-primary-fixed-variant": "#783200",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-md": "24px",
        "stack-sm": "8px",
        "margin-lg": "48px",
        "stack-lg": "32px",
        gutter: "24px",
        "container-max": "1440px",
        "stack-md": "16px",
      },
      fontFamily: {
        "headline-lg-mobile": ["var(--font-syne)", "sans-serif"],
        "body-md": ["var(--font-dm-sans)", "sans-serif"],
        "body-lg": ["var(--font-dm-sans)", "sans-serif"],
        "label-mono": ["var(--font-jetbrains-mono)", "monospace"],
        "headline-lg": ["var(--font-syne)", "sans-serif"],
        "headline-md": ["var(--font-syne)", "sans-serif"],
        "display-lg": ["var(--font-syne)", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-mono": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": ["80px", { lineHeight: "1.0", letterSpacing: "-0.04em", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};

export default config;
